### ISSUE TITLE
output file don't work at "release 0.1.12" 

### ISSUE THREAD

**Issue by kitsudog** [leonchen83/redis-rdb-cli#1]
output file don't work at "release 0.1.12" 
output file size is zero in any case.

same command line is ok at "release 0.1.11" 

centos 7.5
dump.rdb 1000M
openjdk version "1.8.0_191"

**Comment by leonchen83** [comment]
any log at log dir?

**Comment by leonchen83** [comment]
I will revoke this release and test it again

**Comment by leonchen83** [comment]
@kitsudog fixed. please download the new 0.1.12 release
