### ISSUE TITLE
Invalid json when hash value contains double-quote

### ISSUE THREAD

**Issue by billcrook** [leonchen83/redis-rdb-cli#11]
**Describe the bug**
Exported JSON is not valid when hash value contains a double-quote.

**To Reproduce**
1. Set a hash value which contains a double-quote
2. Export the redis db to rdb
3. Use rct to convert to json
```
$ ./rct -f json -s dump.rdb -o dump.json
```
4. Try to parse the json
```
$ jq . dump.json 
```
5. See parse error.
```
parse error: Invalid numeric literal at line 7, column 1849
```
In my case, the value in question appears in the exported JSON as:
```
"geo":"["WW"]"
```

**Expected behavior**
Exported JSON must be valid. The contents of hash values must be escaped properly in the exported JSON.

**Version(please run `rct -v` and paste the information):**  
$ ./rct -v
java -version is less than 1.8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
redis rdb cli: v0.3.0 (d0237a65a95774fdcd4e0aef9eec7e5bf2ab11cf: 2020-01-13T06:55:45+0000)
rct home: ~/redis-rdb-cli/bin/..
java version: 11.0.6, vendor: Oracle Corporation
java home: /usr/lib/jvm/java-11-openjdk
default locale: en, platform encoding: UTF8
os name: Linux, version: 5.5.1-arch1-1, arch: amd64

**Comment by leonchen83** [comment]
will fix at version 0.3.1

**Comment by leonchen83** [comment]
fixed [v0.3.1](https://github.com/leonchen83/redis-rdb-cli/releases/tag/v0.3.1)

**Comment by billcrook** [comment]
Thanks for the quick turnaround. I will test this tonight.

**Comment by billcrook** [comment]
This fixed the issue. I'm seeing some other json parsing issues however. I will create a separate issue. 

Thanks again!
