### ISSUE TITLE
建议size_in_bytes字段以字节单位输出，不格式化，方便脚本分析

### ISSUE THREAD

**Issue by sofire** [leonchen83/redis-rdb-cli#16]
问题1：
rct -f mem 命令 输出 的 size_in_bytes字段 单位不是字节，是格式化后的，不方便用脚本分析。
建议添加 选项，可控制输出格式是 字节还是格式化。

问题2：
rct的size_in_bytes 字段和rdb、USAGE testSet等工具 差距较大。

rct的输出
0,set,"testSet","92.4kB",hash,1000,"10 B",""

python rdb 的输出
0,set,testSet,36436,hashtable,1000,8,

Value at:0x7f94aa585eb0 refcount:1 encoding:hashtable serializedlength:5002 lru:16434941 lru_seconds_idle:425

MEMORY USAGE testSet SAMPLES 0
(integer) 44337

**Comment by leonchen83** [comment]
will fix at version 0.4.1

**Comment by leonchen83** [comment]
fixed
