### ISSUE TITLE
Dynamic custom formatters

### ISSUE THREAD

**Issue by billcrook** [leonchen83/redis-rdb-cli#18]
It might be nice to allow for custom formatters to be developed _without_ the need to fork the repository. Currently, if you want to develop a custom formatter, the main repository needs to be forked and re-built after adding the new formatter to [Format.java](https://github.com/leonchen83/redis-rdb-cli/blob/19add6800316b006625eebe65db52e97376b4b6c/src/main/java/com/moilioncircle/redis/rdb/cli/glossary/Format.java#L37)

For instance:
https://github.com/billcrook/redis-rdb-cli/commit/b3cce93b85322ffe3d34951364fc9cfe9ac8996c#diff-2133dffbf4513d74abdacb9132f74a312f6775830f0763a67c83098c25fc06edR78

An alternative approach might be to allow for dynamic formatters at the command line using a fully qualified path to the new formatter. For instance:
`rct -f com.company.rdb.MyAwesomeFormatter ...`

`MyAwesomeFormatter` could be part of a new jar that is placed in the classpath.

Thanks again for the great tool. I've been using it successfully in production for a number of months now - parsing many gigabytes of rdb files every day.

**Comment by leonchen83** [comment]
@billcrook 
It' a good idea to support custom formatters
We can use java SPI to implement this need like redis-sink-api in [readme.md](https://github.com/leonchen83/redis-rdb-cli#how-to-implement-a-sink-service)

for example I will release an api jar to maven central.
you can dependent that jar and implement your own formatter
```
        <dependency>
            <groupId>com.moilioncircle</groupId>
            <artifactId>redis-rdb-cli-api</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>
```

after build your own project ,you can copy your jar to `lib` folder. `redis-rdb-cli` will found your implement dynamicly. no need use fully qualified path to the new formatter

**Comment by leonchen83** [comment]
this feature will release v0.5.0 after 7 days.

**Comment by billcrook** [comment]
awesome! You might consider relaxing method visibility from private to protected in the base Formatter classes. For instance, `emitZSetJson` or `emitString`. In doing so, custom formatters can leverage functionality in your base visitor classes. I had to do this in order to extend your base classes. For example: https://github.com/billcrook/redis-rdb-cli/commit/b3cce93b85322ffe3d34951364fc9cfe9ac8996c#diff-05443b96f34d75b1a17b1f445e61afef18a5c5ba96740bcd05925d31844dd556R43-R91

**Comment by leonchen83** [comment]
@billcrook 
refer to [implement your formatter](https://github.com/leonchen83/redis-rdb-cli-api#3-implement-your-formatter)
this API not only for json format, you can define your own output format. so I can't add `emitZSetJson `, `emitString` method to this API. also can't change visibility from private to protected . you could copy these methods to your own formatter class.

**Comment by billcrook** [comment]
Thanks again for the great tool!

**Comment by leonchen83** [comment]
@billcrook 
this API for now is not stable. please use it next week.

**Comment by leonchen83** [comment]
@billcrook 
dependent following api jar
```
        <dependency>
            <groupId>com.moilioncircle</groupId>
            <artifactId>redis-rdb-cli-api</artifactId>
            <version>1.4.0</version>
            <scope>provided</scope>
        </dependency>
```
or just use following maven `pom` template 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <groupId>com.your.company</groupId>
    <artifactId>your-sink-service</artifactId>
    <version>1.0.0</version>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.moilioncircle</groupId>
            <artifactId>redis-rdb-cli-api</artifactId>
            <version>1.4.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.moilioncircle</groupId>
            <artifactId>redis-replicator</artifactId>
            <version>3.4.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
            <scope>provided</scope>
        </dependency>
        
        <!-- 
        <dependency>
            your other dependencies
        </dependency>
        -->
        
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

more detail please see test [TestFormatterService](https://github.com/leonchen83/redis-rdb-cli/blob/dev/src/test/java/com/moilioncircle/redis/rdb/cli/ext/rct/TestFormatterService.java) and [FormatterRdbVisitorTest](https://github.com/leonchen83/redis-rdb-cli/blob/dev/src/test/java/com/moilioncircle/redis/rdb/cli/ext/rct/FormatterRdbVisitorTest.java)

**Comment by leonchen83** [comment]
be notice that method name perfix with `apple` in `FormatterService`

for example.
```
applyListZipList
applyListQuickList
...
```
applyListZipList can split 3 parts
1. apply
2. List
3. ZipList
part 2 means redis type
part 3 means redis storage structure.
so if you want parse redis list type, you must implement 3 methods : `applyListZipList` , `applyListQuickList`, `applyList`

**Comment by leonchen83** [comment]
@billcrook 
fixed
download [v0.5.0](https://github.com/leonchen83/redis-rdb-cli/releases/download/v0.5.0/redis-rdb-cli-release.zip)

**Comment by billcrook** [comment]
Fantastic, thank you!
