### ISSUE TITLE
test failure - com.moilioncircle.redis.rdb.cli.ext.rct.FormatterRdbVisitorTest - array lengths differed

### ISSUE THREAD

**Issue by jwaterloo** [leonchen83/redis-rdb-cli#19]
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.moilioncircle.redis.rdb.cli.ext.rct.FormatterRdbVisitorTest
\[    5 B|    2 B/s]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.85 s <<< FAILURE! - in com.moilioncircle.redis.rdb.cli.ext.rct.FormatterRdbVisitorTest
[ERROR] test(com.moilioncircle.redis.rdb.cli.ext.rct.FormatterRdbVisitorTest)  Time elapsed: 2.845 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: array lengths differed, expected.length=299 actual.length=283; arrays first differed at element [10]; expected:<13> but was:<10>
        at com.moilioncircle.redis.rdb.cli.ext.rct.FormatterRdbVisitorTest.test(FormatterRdbVisitorTest.java:41)
Caused by: java.lang.AssertionError: expected:<13> but was:<10>
        at com.moilioncircle.redis.rdb.cli.ext.rct.FormatterRdbVisitorTest.test(FormatterRdbVisitorTest.java:41)

[INFO] Running com.moilioncircle.redis.rdb.cli.glossary.JsonEscapeTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.moilioncircle.redis.rdb.cli.glossary.JsonEscapeTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   FormatterRdbVisitorTest.test:41 array lengths differed, expected.length=299 actual.length=283; arrays first differed at element [10]; expected:<13> but was:<10>
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.599 s
[INFO] Finished at: 2020-11-25T23:03:18-05:00
[INFO] Final Memory: 27M/412M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project redis-rdb-cli: There are test failures.
[ERROR]
[ERROR] Please refer to C:\tutorials\Redis\export-import\redis-rdb-cli\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by leonchen83** [comment]
@jwaterloo 
that because your `/path/to/redis-rdb-cli/src/test/resources/dumpV8-expect.txt` line end at `CRLF` but should be `LF` in your system.
I already fixed the test case. pull code and run test again.
