### ISSUE TITLE
Invalid parsing result after upgrade to redis 6.0.9

### ISSUE THREAD

**Issue by billcrook** [leonchen83/redis-rdb-cli#20]
**Describe the bug**
Parsing an rdb file from redis version 6.0.9 is producing invalid json using the rct command with jsonl format. Previously we were running 5.0.5.
Example invalid result:
```json
{"key":"m:17","value":{"tags":"","":"","":"","description":""},"db":0,"type":"hash"}
```
In another case I see that the source value of `"status":"active"` shows up in json as `"":"active"`.

**To Reproduce**
I have a very large rdb file which I cannot send you for security reasons. I can DM you a dump of one of the broken keys, please let me know where I could send this.

**Expected behavior**
Redis 6+ rdb files should parse correctly.

**Version(run `rct -v` and paste the information):**  
redis rdb cli: v0.4.2

**Comment by billcrook** [comment]
FYI, I used `rdt` to create a small rdb file which reproduces the issue. I would still rather send this to you directly. Thanks.

**Comment by billcrook** [comment]
Note: When using [another parser](https://github.com/sripathikrishnan/redis-rdb-tools), it produces the same invalid json. The root cause is likely due to an invalid rdb file. I will update this ticket with the findings.

**Comment by billcrook** [comment]
Running `redis-check-rdb problem.rdb` fails but rct completes successfully. It might be worth performing a similar validation in redis-rdb-cli.

**Comment by billcrook** [comment]
Related ticket: https://github.com/redis/redis/issues/8124

**Comment by leonchen83** [comment]
run redis dump command and dump 1 invalid key 
send dump string to chen.bao.yi@gmail.com

**Comment by leonchen83** [comment]
redis bug. close issue here.
