### ISSUE TITLE
在prometheus 可以新增监控bigkey ？

### ISSUE THREAD

**Issue by czarea** [leonchen83/redis-rdb-cli#21]
在prometheus怎么监控bigkey啊

**Comment by tao12345666333** [comment]
If you use the latest [dashboard](https://github.com/leonchen83/redis-rdb-cli#dashboard), we have already provided a top N panel.

**Comment by czarea** [comment]
What I want is the top n of bigkey, not the top n of the data type

**Comment by tao12345666333** [comment]
Already in the latest version, but not updated in the document.
