### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by Kikivsantos** [leonchen83/redis-rdb-cli#26]
**Ask a question**
Feel free to ask any question about this tool. no need to fill following table.  

**Describe the bug**

The download is not working when I run the command:
wget https://github.com/leonchen83/redis-rdb-cli/releases/download/${version}/redis-rdb-cli-release.zip
--2021-12-22 16:54:09--  https://github.com/leonchen83/redis-rdb-cli/releases/download//redis-rdb-cli-release.zip
Resolvendo github.com (github.com)... 20.201.28.151
Conectando-se a github.com (github.com)|20.201.28.151|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 404 Not Found
2021-12-22 16:54:10 ERRO 404: Not Found.

What should be the version informed? I tried running to v0.7.2 and still with no success:
wget https://github.com/leonchen83/redis-rdb-cli/releases/v0.7.2/redis-rdb-cli-release.zip

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version(run `rct --version` or `rct -V` and paste the information):**  

**Additional context**

**Comment by leonchen83** [comment]
try 
wget https://github.com/leonchen83/redis-rdb-cli/releases/download/v0.7.2/redis-rdb-cli-release.zip
