### ISSUE TITLE
NOAUTH despite authPassword and/or ACL style on Redis 6.2.6

### ISSUE THREAD

**Issue by sgohl** [leonchen83/redis-rdb-cli#28]
When trying to migrate a RDB file or a single-mode source redis to remote redis cluster (both `6.2.6`)

```
docker run --pull=always -it --rm redisrdbcli/redis-rdb-cli:latest-native bash

# rdt -b redis://192.168.200.177:6161 -o /tmp/data.rdb
/[  1.3GB| 11.6MB/s]

# rmt -s /tmp/data.rdb -m redis://default:UaY34A1KB@192.168.200.177:6071 -r
\[    5 B|  333 B/s]failed to connect cluster nodes, reason : NOAUTH Authentication required.
failed to connect cluster nodes, reason : NOAUTH Authentication required.
failed to connect cluster nodes, reason : NOAUTH Authentication required.
failed to connect cluster nodes, reason : NOAUTH Authentication required.
```

Destination Redis Cluster has:
```
192.168.200.177:6071> ACL LIST
1) "user default on #7d18ca55910168baebd9e6304d988379163eb714a2f524c216299ab377e7451d ~* &* +@all"
```

I also tried the authPassword and ACL style and both:
```
redis://default:UaY34A1KB@192.168.200.177:6071?authPassword=UaY34A1KB
redis://192.168.200.177:6071?authPassword=UaY34A1KB
```

when I try to log in with a wrong password on purpose it recognized the password was wrong, so it works as expected:

```
java.lang.RuntimeException: failed to connect to 192.168.200.177:6071, reason WRONGPASS invalid username-password pair or user is disabled.
	at com.moilioncircle.redis.rdb.cli.cmd.XRmt.getRdbVisitor(XRmt.java:169)
```

It didn't work with the `-c nodes.conf` variant either.

Am I doing something wrong or is the tool not yet able to handle redis v 6.2.6 ?

**Comment by leonchen83** [comment]
@sgohl 
It's a bug. for now can't support redis cluster that with `auth password`. it will fix at version 0.8.2

**Comment by leonchen83** [comment]
@sgohl 
`master` branch fix above bug. you can build a local release by yourself. if test done. it will release in this weekend

**Comment by sgohl** [comment]
yay, with the built master branch it starts syncing, but anyhow it never finishes. 

I know my RDB from source-redis is around 1.4GB , but the process still runs and you can see that the data rate is slowly decreasing (until it arrived at 1.4GB it was around good 15MB/s)

```
/[  1.4GB|  3.4MB/s]
```

**Comment by sgohl** [comment]
oh wait, I read that rst never finishes by design. I'll try with rmt

**Comment by sgohl** [comment]
awesome, with `rmt` it worked perfectly!

**Comment by leonchen83** [comment]
[v0.8.2](https://github.com/leonchen83/redis-rdb-cli/releases/tag/v0.8.2)
