### ISSUE TITLE
expiry is not right

### ISSUE THREAD

**Issue by zwathz** [leonchen83/redis-rdb-cli#36]
**Describe the bug**
the expiry is not right in mem report, example:

```
database,type,key,size_in_bytes,encoding,num_elements,len_largest_element,expiry
0,hash,"run:car:2020091710022104:2020082910002300:1","145 B",ziplist,1,"10 B","+52842-04-02 16:00:00.000"
```

**Version(run `rct --version` or `rct -V` and paste the information):**  
redis rdb cli: v0.9.1 (1f96c81dd4935e2c7fc39f6bb227beede0c8ede4: 2022-05-01T08:10:04+0000)
home: /ccdata/codis_rdb/test/redis-rdb-cli/bin/..
java version: 1.8.0_152, vendor: Oracle Corporation
java home: /opt/src/jdk1.8.0_152/jre
default locale: en, platform encoding: UTF-8
os name: Linux, version: 3.10.0-693.11.6.el7.x86_64, arch: amd64

**Comment by leonchen83** [comment]
@zwathz 
could you run `dump "run:car:2020091710022104:2020082910002300:1"` and paste the result to here?.
and run

**Comment by zwathz** [comment]
> @zwathz could you run `dump "run:car:2020091710022104:2020082910002300:1"` and paste the result to here?
the reason is the key expiry set to long, 1603701080085 s，the result is right.
