### ISSUE TITLE
Check migrated data consistency

### ISSUE THREAD

**Issue by air3ijai** [leonchen83/redis-rdb-cli#40]
**Ask a question**
 We would like to ask to add an option which will help to check migrated data consistency.

 It may be very usefully especially when we have an important data and should guarantee that all is in place.

 Also, sometimes, during [RDB format versions migration](38), we may need to confirm that all is in place and was migrated correctly.

**Additional context**
As for now, we use `info keyspace` to compare number of keys between source and destination, but it's probably is not a better way.

Thank you!

**Comment by leonchen83** [comment]
Hi
After migration.
first run `info keyspace` to compare dataset count.

second open file `/path/to/redis-rdb-cli/log/redis-rdb-cli.log` and check if it contains `failure` text.

if yes. following is the reason of failures.

```
# Key with expired time that already expired in migration. 
# Rdb file has stored expired time by timestamp. so all nodes need NTP to sync time.
failure[expired]...

# Connect to target redis failed. so key migration failed.
failure[failed]...

# Keys are not in the same slot in cluster migration. used in `rst` command
# Example: `del {slot1}:user1 {slot2}:user2`
failure[slot]...

# Some incremental commands are not supported in cluster migration. used in `rst` command
# `publish` `swapdb` `move` `flushall` `flushdb` `multi` `exec` `script flush` `script load` `eval` `evalsha`
failure[unsupported]...
```

**Comment by air3ijai** [comment]
Is there a way to compare somehow all the data, like `shasum` of RDB/AOF or something similar?

**Comment by leonchen83** [comment]
Hi
1. User scenario issues
Compare all data need to scan sourc and target redis.
But after migration or in migration. user may modify that data and key expiration may not be very accurate.(NTP)
So most of the time the data in the these two redis may not be consistent.

2. Implementation issues
Implement a comparison tool need to load source key and the same key in target to memory. if the key is very big. that will consume much memory in comparsion process.

So it is not applicable to implement such a comparison tool in a small usage scenario.

**Comment by air3ijai** [comment]
Thank you for the clarifications,  so as for now we have just methods you described
1. `info keyspace`
2. `redis-rdb-cli/log/redis-rdb-cli.log`
3. Check some random Redis keys on source and destination

**Comment by leonchen83** [comment]
FYI
[fast and efficient parallelized comparison of redis databases](https://redis.com/blog/fast-and-efficient-parallelized-comparison-of-redis-databases/)
