### ISSUE TITLE
Adding any -k parameter returns an empty list

### ISSUE THREAD

**Issue by tobias-zeptio** [leonchen83/redis-rdb-cli#64]
**Ask a question**
Can't get key filter to work with rct

`rct -f json -s dump.rdb -o anno.json -k annotations:thing:*`

**To Reproduce**

Result without -k parameter set

```
[
  {
    "key": "annotations:thing:2b5b90aa",
    "value": "{}",
    "db": 0,
    "type": "string",
    "expiry": 1691764906330
  }
]
```
Result with -k annotations:thing:*, or -k *.

```
[]
```

**Expected behavior**
-k should filter in the "key" value

**Version(run `rct --version` or `rct -V` and paste the information):**  

Running in the `redisrdbcli/redis-rdb-cli:latest-native` container.

redis rdb cli: v0.9.5 (0e2d1c52e3d441ffd992f4331baea896a0d0e44c: 2023-12-11T04:01:33+0000)
home: /app/redis-rdb-cli/bin/..
java version: 11.0.15, vendor: Oracle Corporation
platform encoding: UTF-8
os name: Linux, version: 6.1.0-17-amd64, arch: amd64

**Comment by leonchen83** [comment]
Hi
try `rct -f json -s dump.rdb -o anno.json -k "annotations:thing:.*"` and `rct -f json -s dump.rdb -o anno.json -k ".+"`

**Comment by tobias-zeptio** [comment]
That did it! Thank you!

Should the documentation be updated to reflect this?

**Comment by leonchen83** [comment]
English is not my native language. so welcome to PR

**Comment by tobias-zeptio** [comment]
Looking at the examples again I just misunderstood it.

I don't think there is a need to update it, especially not with this issue as documentation.
