### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by jayvdb** [leonchen83/redis-rdb-cli#66]
I like to run java tools using https://github.com/scijava/jgo , which requires that the package is hosted on a maven repository

**Comment by leonchen83** [comment]
Hi
This Java library is not suitable for publishing to Maven because it already contains relevant Bash script files. Could you consider using Docker to run it instead?

**Comment by jayvdb** [comment]
I guess you are referring to the scripts at https://github.com/leonchen83/redis-rdb-cli/tree/master/src/main/assembly/bin 

I don't need those scripts when I use https://github.com/scijava/jgo , which is much more efficient that using docker as it uses my local maven cache.

**Comment by leonchen83** [comment]
If you want to use jgo, you can try packaging and publishing it to GitHub Packages yourself, similar to the example here: [https://github.com/billcrook/redis-rdb-cli/packages/481686](https://github.com/billcrook/redis-rdb-cli/packages/481686).

**Comment by jayvdb** [comment]
Well the idea is that the package is distributed as part of each release here in this repo.  If you preferred to publish it to GitHub Packages on this repo, that would be wonderful.  I can get jgo to use that repository also.

**Comment by leonchen83** [comment]
The demand for this is not significant at the moment. If others have a similar issue in the future, I'll upload redis-rdb-cli to the Maven Central Repository then. So currently, you can fork the project and execute `mvn clean install` to install it to the local `~/.m2` directory.
