### ISSUE TITLE
Compatibility of redis-rdb-cli with Redis and KeyDB versions

### ISSUE THREAD

**Issue by zpomal** [leonchen83/redis-rdb-cli#74]
**Ask a question**

Hi,
I have the following setup and question regarding data migration:

Current setup:
Redis DB: REDIS0011 with redis-ver7.2.4

Target setup:
KeyDB: REDIS0009 with redis-ver6.3.4

I would like to migrate from Redis to KeyDB and I am planning to use redis-rdb-cli for this process. My question is: will redis-rdb-cli understand the dump format from REDIS0011 (redis-ver7.2.4)?

Thank you for your assistance.

Best regards,
zpomal

**Comment by leonchen83** [comment]
@zpomal 
Not yet support `REDIS0011`
next version will support this above

**Comment by zpomal** [comment]
Great answer! 
Thanks a lot for your help!
